import { FinancialGoal, FinancialTask, ShopItem } from '../types/gameTypes';

// 1. Финансовые цели (не менее 3 по ТЗ 2.6)
export const INITIAL_GOALS: FinancialGoal[] = [
  {
    id: 'goal_paints',
    title: 'Набор масляных красок',
    category: 'Комната юного художника',
    totalCost: 160,
    savedAmount: 35,
    description: 'Финни мечтает о настоящих масляных красках, чтобы написать первую большую картину!',
    iconName: 'gold_bars',
  },
  {
    id: 'goal_easel',
    title: 'Деревянный мольберт',
    category: 'Студия мастера',
    totalCost: 250,
    savedAmount: 0,
    description: 'Устойчивый буковый мольберт позволит Финни рисовать пейзажи стоя, как настоящий мастер.',
    iconName: 'easel',
  },
  {
    id: 'goal_exhibition',
    title: 'Первая выставка картин',
    category: 'Большая мечта',
    totalCost: 400,
    savedAmount: 0,
    description: 'Организация персональной выставки в городском музее для всех друзей зверят!',
    iconName: 'trophy',
  },
];

// 2. Каталог покупок (не менее 8 позиций двух типов по ТЗ 2.6: обязательные и необязательные)
export const INITIAL_SHOP_ITEMS: ShopItem[] = [
  // --- ОБЯЗАТЕЛЬНЫЕ РАСХОДЫ (Еда и уход) ---
  {
    id: 'food_carrot',
    title: 'Сладкая морковка',
    type: 'mandatory',
    category: 'food',
    price: 5,
    iconName: 'carrot',
    satietyBoost: 25,
    moodBoost: 5,
    description: 'Полезный хрустящий завтрак. Необходим Финни для сил и хорошего самочувствия.',
  },
  {
    id: 'food_apple',
    title: 'Спелое яблоко',
    type: 'mandatory',
    category: 'food',
    price: 4,
    iconName: 'apple',
    satietyBoost: 20,
    moodBoost: 5,
    description: 'Витаминный перекус между уроками рисования.',
  },
  {
    id: 'care_brush',
    title: 'Щёточка для ухода',
    type: 'mandatory',
    category: 'care',
    price: 8,
    iconName: 'brush_care',
    satietyBoost: 0,
    moodBoost: 20,
    description: 'Регулярная гигиена и чистка шерстки — важная обязательная часть заботы о питомце.',
  },
  {
    id: 'care_tea',
    title: 'Витаминный сбор',
    type: 'mandatory',
    category: 'care',
    price: 10,
    iconName: 'tea',
    satietyBoost: 30,
    moodBoost: 15,
    description: 'Тёплый травяной сбор для укрепления здоровья в прохладную погоду.',
  },

  // --- НЕОБЯЗАТЕЛЬНЫЕ РАСХОДЫ (Развлечения, одежда, декор) ---
  {
    id: 'art_palette',
    title: 'Холст и палитра',
    type: 'discretionary',
    category: 'art',
    price: 25,
    iconName: 'palette',
    satietyBoost: 0,
    moodBoost: 35,
    description: 'Яркие цвета вдохновляют Финни на создание новых шедевров.',
  },
  {
    id: 'art_tube_paints',
    title: 'Тюбики с краской',
    type: 'discretionary',
    category: 'art',
    price: 15,
    iconName: 'paint_tubes',
    satietyBoost: 0,
    moodBoost: 25,
    description: 'Дополнительные оттенки для смешивания на палитре.',
  },
  {
    id: 'clothes_scarf',
    title: 'Вязаный шарф',
    type: 'discretionary',
    category: 'clothes',
    price: 18,
    iconName: 'scarf',
    satietyBoost: 0,
    moodBoost: 25,
    description: 'Мягкий шерстяной шарфик согреет на прогулке в парке.',
  },
  {
    id: 'clothes_beret',
    title: 'Берет художника',
    type: 'discretionary',
    category: 'clothes',
    price: 22,
    iconName: 'beret',
    satietyBoost: 0,
    moodBoost: 30,
    description: 'Стильный бордовый берет придаёт Финни образ настоящего мастера.',
  },
  {
    id: 'furniture_easel',
    title: 'Учебный мольберт',
    type: 'discretionary',
    category: 'furniture',
    price: 40,
    iconName: 'easel',
    satietyBoost: 0,
    moodBoost: 45,
    description: 'Компактный деревянный мольберт для рабочего стола.',
  },
  {
    id: 'furniture_chair',
    title: 'Уютное кресло',
    type: 'discretionary',
    category: 'furniture',
    price: 35,
    iconName: 'chair',
    satietyBoost: 0,
    moodBoost: 40,
    description: 'Мягкое кресло, где приятно отдыхать и читать книги по искусству.',
  },
];

// 3. Финансовые задания (не менее 6 заданий по 3 темам по ТЗ 2.6)
export const INITIAL_TASKS: FinancialTask[] = [
  // ТЕМА 1: ПЛАНИРОВАНИЕ БЮДЖЕТА
  {
    id: 'task_budget_1',
    theme: 'budget',
    themeTitle: 'Планирование бюджета',
    title: 'Карманные деньги на неделю',
    scenario: 'Финни получил 30 монет на неделю. Ему обязательно нужна еда (10 монет), а ещё он хочет купить красивый значок за 20 монет. Как поступить?',
    reward: 10,
    completed: false,
    options: [
      {
        id: 'tb1_opt1',
        text: 'Сначала отложить 10 монет на еду, 10 монет в копилку, а значок купить позже',
        isCorrect: true,
        explanation: 'Отлично! Обязательные расходы всегда планируются в первую очередь, а накопления помогают быстрее достичь цели.',
        rewardChange: 10,
        moodChange: 20,
        satietyChange: 25,
      },
      {
        id: 'tb1_opt2',
        text: 'Потратить 20 монет сразу на значок, а на еду оставить то, что останется',
        isCorrect: false,
        explanation: 'Осторожно! Если сразу потратить почти все деньги на значок, Финни останется голодным. Всегда сначала обеспечь обязательные потребности!',
        rewardChange: 3,
        moodChange: -10,
        satietyChange: -15,
      },
    ],
  },
  {
    id: 'task_budget_2',
    theme: 'budget',
    themeTitle: 'Планирование бюджета',
    title: 'Поход в художественный магазин',
    scenario: 'У Финни есть 25 монет. Для завершения картины ему необходима чёрная краска (8 монет). Также на витрине лежит блестящая наклейка за 20 монет.',
    reward: 10,
    completed: false,
    options: [
      {
        id: 'tb2_opt1',
        text: 'Купить нужную краску за 8 монет, а 17 монет отложить на будущие материалы',
        isCorrect: true,
        explanation: 'Правильное решение! Покупка нужного материала позволила закончить работу, а остаток спасён от импульсивных трат.',
        rewardChange: 10,
        moodChange: 25,
      },
      {
        id: 'tb2_opt2',
        text: 'Купить наклейку за 20 монет, а краску не покупать',
        isCorrect: false,
        explanation: 'Картина осталась незавершённой. Наклейка порадовала на минуту, но цель так и не была выполнена. Необязательные покупки лучше совершать после важных.',
        rewardChange: 2,
        moodChange: -5,
      },
    ],
  },

  // ТЕМА 2: ФОРМИРОВАНИЕ СБЕРЕЖЕНИЙ
  {
    id: 'task_savings_1',
    theme: 'savings',
    themeTitle: 'Формирование сбережений',
    title: 'Копилка мечты: шаг за шагом',
    scenario: 'Финни мечтает накопить на набор красок (160 монет). Сейчас у него есть 15 свободных монет. Что с ними сделать?',
    reward: 10,
    completed: false,
    options: [
      {
        id: 'ts1_opt1',
        text: 'Отправить 10 монет в копилку цели, а 5 оставить на мелкие расходы',
        isCorrect: true,
        explanation: 'Замечательно! Регулярные небольшие отчисления в копилку — главный секрет достижения больших финансовых целей.',
        rewardChange: 10,
        moodChange: 20,
      },
      {
        id: 'ts1_opt2',
        text: 'Купить три сладких леденца прямо сейчас, ведь цель ещё далеко',
        isCorrect: false,
        explanation: 'Если тратить все карманные деньги на сиюминутные сладости, цель будет откладываться бесконечно. Лучше соблюдать баланс!',
        rewardChange: 2,
        moodChange: 5,
      },
    ],
  },
  {
    id: 'task_savings_2',
    theme: 'savings',
    themeTitle: 'Формирование сбережений',
    title: 'Непредвиденные расходы',
    scenario: 'У Финни неожиданно сломалась кисть для рисования. Новая стоит 12 монет. Откуда правильнее взять средства?',
    reward: 10,
    completed: false,
    options: [
      {
        id: 'ts2_opt1',
        text: 'Выполнить задание в парке и заработать монеты, не трогая копилку мечты',
        isCorrect: true,
        explanation: 'Превосходно! Сохранение неприкосновенности копилки помогает не сорвать финансовый план и воспитывает дисциплину.',
        rewardChange: 12,
        moodChange: 20,
      },
      {
        id: 'ts2_opt2',
        text: 'Разбить копилку и потратить накопления на краски',
        isCorrect: false,
        explanation: 'Снятие денег из целевой копилки отдаляет мечту. На непредвиденные нужды лучше иметь небольшой резервный фонд или заработать дополнительно.',
        rewardChange: 3,
        moodChange: -10,
      },
    ],
  },

  // ТЕМА 3: ПЛАТЕЖИ И ПОКУПКИ
  {
    id: 'task_payments_1',
    theme: 'payments',
    themeTitle: 'Платежи и покупки',
    title: 'Выбираем в продуктовой лавке',
    scenario: 'Финни проголодался. В лавке есть свежая морковка за 5 монет (+25 сытости) и огромный леденец за 15 монет (+5 сытости). Баланс: 18 монет.',
    reward: 10,
    completed: false,
    options: [
      {
        id: 'tp1_opt1',
        text: 'Купить полезную морковку за 5 монет: сытно, полезно и экономно',
        isCorrect: true,
        explanation: 'Идеальный выбор! Соотношение цены и пользы отличное: Финни наелся, и у него осталось 13 монет на другие дела.',
        rewardChange: 10,
        moodChange: 15,
        satietyChange: 30,
      },
      {
        id: 'tp1_opt2',
        text: 'Купить дорогой леденец за 15 монет',
        isCorrect: false,
        explanation: 'Леденец вкусный, но сытости почти не дал, а почти все деньги закончились. Обращай внимание на реальную ценность товара!',
        rewardChange: 2,
        moodChange: 10,
        satietyChange: 5,
      },
    ],
  },
  {
    id: 'task_payments_2',
    theme: 'payments',
    themeTitle: 'Платежи и покупки',
    title: 'Акция и разумный выбор',
    scenario: 'В магазине проходит акция: 2 тюбика краски за 20 монет (вместо 30 по отдельности). Финни сейчас нужен только 1 тюбик. Как поступить?',
    reward: 10,
    completed: false,
    options: [
      {
        id: 'tp2_opt1',
        text: 'Если второй цвет точно пригодится для картины — взять по акции, сэкономив 10 монет',
        isCorrect: true,
        explanation: 'Мудрый расчёт! Покупка нужного набора со скидкой позволяет экономить бюджет на вещах, которые всё равно потребуются.',
        rewardChange: 10,
        moodChange: 25,
      },
      {
        id: 'tp2_opt2',
        text: 'Купить 5 разных наборов по акции, заняв недостающие монеты',
        isCorrect: false,
        explanation: 'Скидка — не повод покупать то, что не укладывается в бюджет или сейчас не нужно. Избегай спонтанных переплат!',
        rewardChange: 2,
        moodChange: -5,
      },
    ],
  },
];

// 4. Описания стадий роста питомца (не менее 3 по ТЗ 2.6)
export const PET_STAGES = [
  {
    stage: 1,
    title: 'Малыш-художник',
    subtitle: 'Учится отличать обязательные траты от желаний',
    minPeriods: 1,
    bonuses: '+5 монет к доходу периода',
  },
  {
    stage: 2,
    title: 'Юный мастер',
    subtitle: 'Уверенно планирует бюджет и пополняет копилку',
    minPeriods: 3,
    bonuses: '+10 монет к доходу периода, скидка 10% в лавке',
  },
  {
    stage: 3,
    title: 'Мастер-иллюстратор',
    subtitle: 'Финансово грамотный кролик с собственной студией',
    minPeriods: 5,
    bonuses: '+20 монет к доходу периода, статус Эксперта',
  },
];

// 5. Образовательный справочник для детей и родителей (ТЗ 2.5.11 и 2.5.12)
export const FINANCIAL_TERMS = [
  {
    term: 'Обязательные расходы',
    childDesc: 'То, без чего нельзя обойтись каждый день: полезная еда, забота о здоровье и тёплый дом.',
    parentNote: 'Основа личного бюджета (компетенция 1-2 Единой рамки).',
  },
  {
    term: 'Необязательные расходы (желания)',
    childDesc: 'Приятные покупки для радости и настроения: игрушки, сладости, украшения. Их можно отложить.',
    parentNote: 'Развивает критическое мышление и отложенное вознаграждение.',
  },
  {
    term: 'Сбережения и Копилка',
    childDesc: 'Часть денег, которую мы прячем в надёжное место, чтобы накопить на большую мечту.',
    parentNote: 'Формирует культуру целеполагания и финансовой подушки безопасности.',
  },
  {
    term: 'План и Факт',
    childDesc: 'План — это как мы договорились потратить монеты. Факт — то, как мы их потратили на самом деле.',
    parentNote: 'Инструмент самоконтроля и анализа принятых решений.',
  },
];
